### ISSUE TITLE
Enhancement: restarting extension = Uncaught Error: Extension context invalidated.

### ISSUE THREAD

**Issue by raszpl** [Tampermonkey/tampermonkey#1088]
##  Expected Behavior

restarting tampermonkey doesnt disturb already injected scripts

## Actual Behavior

    Uncaught Error: Extension context invalidated.
        at Object.sendMessage (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/rea/common.js:4)
        at HTMLDocument.<anonymous> (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/content.js:22)

Isnt the end of the world, but GM functions like GM_xmlhttpRequest no longer work

## Specifications

- Chromium: 86.0.4240.112
- TM: 4.12.6121
- OS: win10

## proposed solution

port.onDisconnect.addListener attempting to reconnect as per: https://stackoverflow.com/questions/10994324/chrome-extension-content-script-re-injection-after-upgrade-or-install/11598753#11598753

**Comment by derjanb** [comment]
Will check 👍

**Comment by derjanb** [comment]
Should be fixed at 5.5.6233 ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review)

Please download the crx file linked above and drag and drop it to the extensions page `chrome://extensions` or wait for the Chrome Web Store review being done.

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by raszpl** [comment]
I inject span and put onclick on it
```
	...
	zNode.innerHTML ='<span class="moovis_mysize"></span>';
	where.prepend(zNode);
	urlsize(zNode);
	document.querySelector(".moovis_mysize").onclick = ()=>{
		urlsize(zNode);
	}
```
urlsize calls GM_xmlhttpRequest with referer.
When page loads it automatically calls urlsize(zNode) and fills <span> with size so I know it works.
I then restart Tampermonkey BETA 5.5.6235
and click the button:

```
Uncaught Error: Extension context invalidated.
    at Object.connect (content.js:32:218)
    at as (content.js:38:287)
    at xhr (content.js:49:341)
    at Object.processConnect (content.js:62:20)
    at content.js:90:311
    at Object.message (content.js:18:413)
    at content.js:91:26
    at v (content.js:70:410)
connect @ content.js:32
as @ content.js:38
xhr @ content.js:49
processConnect @ content.js:62
(anonymous) @ content.js:90
message @ content.js:18
(anonymous) @ content.js:91
v @ content.js:70
the_page:1 Access to XMLHttpRequest at 'https://actualaddress.extension' from origin 'https://blabla.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
userscript.html?name=moovis.user.js&id=2da021b9-3051-4505-a981-bdae5e41673c:2935 onerror https://actualaddress.extension 0 
content.js:32 Uncaught Error: Extension context invalidated.
    at Object.connect (content.js:32:218)
    at as (content.js:38:287)
    at xhr (content.js:49:341)
    at Object.processConnect (content.js:62:20)
    at content.js:90:311
    at Object.message (content.js:18:413)
    at content.js:91:26
    at v (content.js:70:410)
```

edit: 
aaa, looked into ([crx](https://tampermonkey.net/crx/tampermonkey_beta_current.crx)|xpi in review) manuifest and see "version": "5.5.6236", so 

>Should be fixed at 5.5.6233

is was a typo, will check it next

**Comment by raszpl** [comment]
drag/dropped 5.5.6236 and it updated, restarted browser for good measure. Same results with Uncaught Error: Extension context invalidated.

**Comment by derjanb** [comment]
You're right. I confused this with service worker restart issues. 
The problem is, I don't see a way to fix this. I could hide the error, but that's just a cosmetic fix.

Why do you need to restart the extension?

**Comment by raszpl** [comment]
I really dont :) I think I was just messing in other extension and stumbled onto something I thought was a solution. You can totally disregard whole thing.
