### ISSUE TITLE
Userscript stopped working. TamperMonkey error: TypeError: Message length exceeded maximum allowed length.

### ISSUE THREAD

**Issue by Ark-kun** [Tampermonkey/tampermonkey#1787]
I have a userscript I've written. It uses GM.getValue and GM.setValue to store some short JSON data pieces. The total size of the levelDB is 23MB.
Suddenly the userscript stopped working.

## Expected Behavior
I expect the script to work.

## Actual Behavior

The userscript function is now not getting executed at all.
The `background.html` console shows the following error:
```
Error in event handler: TypeError: Message length exceeded maximum allowed length.
    at chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/background.js:831:495
    at chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/background.js:826:329
    at u (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/background.js:620:57)
    at Object.<anonymous> (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/background.js:620:214)
    at o (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/background.js:210:91)
    at s (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/background.js:209:461)
    at Object.always (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/background.js:210:200)
    at chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/background.js:620:200
    at Object.run (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/background.js:620:228)
    at Object.exec (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/background.js:826:228)
```

When I go to the Storage tab of the script, the loading ring just spins forever.

## Specifications

- Chrome: Version 113.0.5672.127 (Official Build) (64-bit)
- TM: 4.18.1
- OS: Windows 10

**Comment by Ark-kun** [comment]
Oh my... I found out that TM writes all key-value pairs as a single JSON string value in levelDB...
Its... an... interesting... design... choice...

Nevertheless, it looks like TM is parsing all those values on startup. And somehow failing despite the values totaling pretty modest ~73 MB.

I've tried to rename my script, hoping that TML won't read the old value, but this didn't work.

**Comment by derjanb** [comment]
Please try the fopllowing: set "Config Mode" to "Advanced" and then "Content Script API" to "UserScripts API Dynamic". This makes Tampermonkey pre-register the script including storage.

**Comment by PoLaKoSz** [comment]
Thank You derjanb for the fast response!
Changing the setting to Dynamic only caused the script to show up in the list (when clicking on the Tampermonkey icon) but the script still not executed.
Is there a way to access the storage other than Tampermonkey UI?

**Comment by derjanb** [comment]
You can debug into the service worker and check the storage at the "Application" Tab > Storage > Extension storage > Local.
Now search for the key `@st#` + your script's UUID.

![Image](https://github.com/user-attachments/assets/e4b01c1e-281c-43cd-b5e4-133694dd543b)
