### ISSUE TITLE
GM.xmlHttpRequest arraybuffer bug on Brave beta

### ISSUE THREAD

**Issue by TuxedoTako** [Tampermonkey/tampermonkey#2056]
There is an issue with `responseType: 'arraybuffer'` on `GM.xmlHttpRequest` on Brave beta. This also happens on Violentmonkey: https://github.com/violentmonkey/violentmonkey/issues/2098, so it might be an issue on Brave's side.

## Expected Behavior

The request works, or the `onerror` callback is called.

## Actual Behavior

```
TypeError: Failed to fetch
    at VM124 content.js:42:125
    at wn (VM124 content.js:14:45)
    at Object.toBlob (VM124 content.js:42:90)
    at VM124 content.js:43:201
    at wn (VM124 content.js:14:45)
    at VM124 content.js:43:127
    at s (VM124 content.js:41:170)
    at VM124 content.js:41:247
```

This error isn't propagated to the `onerror` callback.

## Specifications

- Brave 1.67.78 Chromium: 125.0.6422.41 (Official build) beta (64-bits)
- TM: 5.1.1
- OS: Windowz 10

## Script

```js
// ==UserScript==
// @name         GM.xmlHttpRequest arraybuffer bug
// @namespace    http://tampermonkey.net/
// @version      0.0.0
// @description  Reproduce a bug on brave beta
// @author       Tuxedo Takodachi
// @match        https://github.com/*
// @grant        GM.xmlHttpRequest
// @grant        GM_registerMenuCommand
// @connect      www.tampermonkey.net
// ==/UserScript==

(function () {
    'use strict';

    GM_registerMenuCommand('test', e => {
        GM.xmlHttpRequest({
            method: "GET",
            url: 'https://www.tampermonkey.net/images/ape.svg',
            responseType: 'arraybuffer',
            onload(xhr) {
                console.log(xhr);
            },
            onerror(e) {
                console.error(e);
            },
            onabort(e) {
                console.error(e);
            },
        });
    });
})();
```

If `responseType: 'arraybuffer',` is commented out, the request works.

**Comment by derjanb** [comment]
Fixed at Brave. https://github.com/brave/brave-browser/issues/38256

Thanks for reporting!
