### ISSUE TITLE
OutOfMemory on Android (Dolphin)

### ISSUE THREAD

**Issue by kkot** [Tampermonkey/tampermonkey#222]
I get the following exception when trying to run a userscript on Dolphin that works on Chrome. Size of script is 850 lines long and 21KB size.

```
E/art﹕ Throwing OutOfMemoryError "Failed to allocate a 57283554 byte allocation with 16777120 free bytes and 34MB until OOM"
W/System.err﹕ java.lang.OutOfMemoryError: Failed to allocate a 57283554 byte allocation with 16777120 free bytes and 34MB until OOM
W/System.err﹕ at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
W/System.err﹕ at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:133)
W/System.err﹕ at java.lang.StringBuilder.append(StringBuilder.java:124)
W/System.err﹕ at org.json.JSONStringer.string(JSONStringer.java:344)
W/System.err﹕ at org.json.JSONStringer.value(JSONStringer.java:252)
W/System.err﹕ at org.json.JSONObject.writeTo(JSONObject.java:720)
W/System.err﹕ at org.json.JSONStringer.value(JSONStringer.java:237)
W/System.err﹕ at org.json.JSONArray.writeTo(JSONArray.java:613)
W/System.err﹕ at org.json.JSONStringer.value(JSONStringer.java:233)
W/System.err﹕ at org.json.JSONObject.writeTo(JSONObject.java:720)
W/System.err﹕ at org.json.JSONStringer.value(JSONStringer.java:237)
W/System.err﹕ at org.json.JSONObject.writeTo(JSONObject.java:720)
W/System.err﹕ at org.json.JSONObject.toString(JSONObject.java:689)
W/System.err﹕ at java.lang.String.valueOf(String.java:1506)
W/System.err﹕ at org.json.JSON.toString(JSON.java:90)
W/System.err﹕ at org.json.JSONObject.getString(JSONObject.java:551)
W/System.err﹕ at net.tampermonkey.ChromeEmulation$JsInterface.invoke(Unknown Source)
W/System.err﹕ at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err﹕ at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err﹕ at android.os.Looper.loop(Looper.java:155)
W/System.err﹕ at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by derjanb** [comment]
Which device do you use and how much RAM does it have?

I guess there is not much that I can do for you, cause TM is not written in the "native Android language" Java but in Javascript. This causes a considerable amount more resource usage for the benefit of sharing almost all Code with the Chrome extension.

**Comment by kkot** [comment]
I use HTC One (M8) which has 2 GB of RAM. 

My userscript has a lot of @include maybe it is the problem because 850 lines of code doesn't seam much.

**Comment by derjanb** [comment]
Hmm, this really shouldn't be too much. I often do some tests with the [Webcomic Reader script](https://github.com/ameboide/webcomic_reader). It has ~750 includes and is working fine here.
Are you common with ADB? You can debug the TM background page as described [here](https://developer.chrome.com/devtools/docs/remote-debugging).

Maybe you'll discover something interesting?

**Comment by derjanb** [comment]
TM Dolphin 4.0.5005 now needs less memory for external resources (@require and @external). Do you still see this issue?

**Comment by kkot** [comment]
For me nothing changed. Stacktrace looks similar. Script works in Chrome but on Dolphin not.
```
E/art﹕ Throwing OutOfMemoryError "Failed to allocate a 57283554 byte allocation with 16777120 free bytes and 34MB until OOM"
W/System.err﹕ java.lang.OutOfMemoryError: Failed to allocate a 57283554 byte allocation with 16777120 free bytes and 34MB until OOM
W/System.err﹕ at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
W/System.err﹕ at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:133)
W/System.err﹕ at java.lang.StringBuilder.append(StringBuilder.java:124)
W/System.err﹕ at org.json.JSONStringer.string(JSONStringer.java:344)
W/System.err﹕ at org.json.JSONStringer.value(JSONStringer.java:252)
W/System.err﹕ at org.json.JSONObject.writeTo(JSONObject.java:720)
W/System.err﹕ at org.json.JSONStringer.value(JSONStringer.java:237)
W/System.err﹕ at org.json.JSONArray.writeTo(JSONArray.java:613)
W/System.err﹕ at org.json.JSONStringer.value(JSONStringer.java:233)
W/System.err﹕ at org.json.JSONObject.writeTo(JSONObject.java:720)
W/System.err﹕ at org.json.JSONStringer.value(JSONStringer.java:237)
W/System.err﹕ at org.json.JSONObject.writeTo(JSONObject.java:720)
W/System.err﹕ at org.json.JSONObject.toString(JSONObject.java:689)
W/System.err﹕ at java.lang.String.valueOf(String.java:1506)
W/System.err﹕ at org.json.JSON.toString(JSON.java:90)
W/System.err﹕ at org.json.JSONObject.getString(JSONObject.java:551)
W/System.err﹕ at net.tampermonkey.ChromeEmulation$JsInterface.invoke(Unknown Source)
W/System.err﹕ at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err﹕ at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err﹕ at android.os.Looper.loop(Looper.java:155)
W/System.err﹕ at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by derjanb** [comment]
This is a device/android limitation.
