### ISSUE TITLE
onUserScriptMessage and onUserScriptConnect sometimes not available in MV3-enabled browsers

### ISSUE THREAD

**Issue by Plinko650** [Tampermonkey/tampermonkey#2237]
tampermonkey wont open as an extintion and wont let me use and scrips

**Comment by derjanb** [comment]
Tampermonkey and Browser version?

**Comment by feyrhysand** [comment]
Tampermonkey on Chrome no longer opens. When I click on it, a loading wheel appears for a minute or two. Afterwards, I got an error message
![Capture](https://github.com/user-attachments/assets/17e41d74-212c-4952-93ef-464a4a003e49)
![Capture2](https://github.com/user-attachments/assets/7ceea69d-92d9-4107-9482-08c1cd9ad423)

**Comment by derjanb** [comment]
Please go to "chrome://extensions" and disable and re-enable Tampermonkey. Does that solve the issue?

**Comment by slysnake96** [comment]
> Please go to "chrome://extensions" and disable and re-enable Tampermonkey. Does that solve the issue?

I have also been having this exact same issue as well, and for me reloading the extension works but only on a per tab/page basis.
For example, if I have a youtube video open, then close that tab and then re-open a new youtube video in a new tab the extension needs to be reloaded every time I do that.
FYI, I use the latest version of Vivaldi as my web browser.
Not sure if my explanation will be helpful at all but that seems to be what happens and works for me.
I really hope a fix for this issue is found soon.

**Comment by filbo** [comment]
Hi, I am having the same syndrome on a significantly different setup.

I'm running really old stuff, so you can chastise me for that, but everything **was** working until my system was rebooted by an hours-long power outage.

System: LinuxMint 17.3 (Ubuntu 14.04-based); yes, completely ancient.

Browser: Opera 88.0.4401.0, from 'opera-dev' channel, also completely ancient; newest version which will install on my incredibly old OS runtime.  Underlying Chromium version is 102.0.4972.0.  'Developer mode' is enabled in opera:extensions.

TM: 5.3.6216, beta from the Chrome 'store'.  **Likely hint**: I think I was running a 5.1.x beta before the reboot; I had recently noticed that the TM dashboard still reported 5.1.x (don't remember x) in its titlebar, despite Opera's extensions manager saying 5.3.x.

I start Opera and go to a site where I use a TM userscript, and the script is not active.

I open TM dashboard and after 10 seconds of blank screen it pops up:

> Tampermonkey BETA
> 
> An internal error occurred. If this problem persists after a restart of the browser, please press OK and report this issue at the forum.
> 
> Do you want to visit the Tampermonkey forum?

If I open the browser inspector from that blank dashboard (after first closing the popup) -- I see:

> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'addListener')
>     at Object.addListener (background.js:246:420)
>     at Object.init (background.js:1025:14)
>     at background.js:1054:202
>     at background.js:1076:377
>     at background.js:1076:383
>     at background.js:1076:387

The same exact trace is available via opera:extensions > TM > Details > Inspect views > options.html **OR** service worker (both threads are aborted in the same state).

background.js:246:420, when prettyprinted, looks like:

```
        onMessage: {
          ...Le.onMessage,
          addListener: e=>{
            if (!mt)
              throw new Error("extension.onMessage listener can only be registered during startup in non-persistent background pages!");
            const t = (t,n,r)=>e(t, n, r);
            Ce.runtime.onUserScriptMessage.addListener(t),  /* ERROR HERE */
            Le.onMessage.addListener(t)
          }
        }
```
i.e. `Ce.runtime.onUserScriptMessage` is undefined.

I cannot change any TM settings as I can't reach the settings UI.  Before the reboot, I believe 'sandbox' was 'default' and 'change CSP' was 'always', or whatever the lowest-security choice is called.

Also: clicking the TM icon on Opera toolbar results in the same whirling blue/green bars.

Restarting Opera does not help.

Disabling and re-enabling TM in opera:extensions does not help.

**Comment by filbo** [comment]
Commenting out the references to `Ce.runtime.onUserScriptConnect` and `Ce.runtime.onUserScriptMessage` in my copy of background.js allowed TM to come up far enough to open its 'you're running a new version' browser tab, but I still couldn't get to dashboard.

Commenting them out in extensions.js lets me reach the dashboard.  At that point there are no errors in the options.html or service worker consoles, and I can edit userscripts, but they still do not **work**.

The top of the dashboard (and the top of the browser toolbar icon menu) has a message '**Please enable developer mode to allow userscript injection. Click here for more info how to do this.**'.  But this is already enabled.  Toggling it, disabling/enabling TM, does not help.

It seems like TM has been recoded to use newer browser APIs which exist only on newer browsers (oddly enough :).  I thought that by commenting out the newer one, the other code that looked like maybe using an older API would shine through, but it is not sufficient.

The 4 patches I applied are all of this same general form: a bit of code is calling `onUserScriptWhazzat...addListener(...), OnWhazzat...addListener(...)`, I comment out the first call so only the 2nd one happens (and returns the value of the 2nd one, as was going to be the case before commenting):
`({onConnect:{addListener:function(e){return /*_e.runtime.onUserScriptConnect.addListener(e),*/_e.runtime.onConnect.addListener(e)}`

... which gets me into dashboard, which is good since I can now backup any in-progress user script edits; but not good, since I still can't get them to run.

**Comment by filbo** [comment]
My issue is fixed -- likely only in a temporary fashion.

After getting 5.3.6216-beta-chrome working well enough to save settings, I disabled it and enabled(*) 5.1.6194-release-opera, restored settings, and my userscripts are working once again.  I expect this to hold as long as TM-release-opera is not updated to the point where it can no longer fall back to the APIs found in my ancient Opera browser.

[ (*)I have 3x TM installed in the browser, but never more than one enabled at the same time: opera-release, chrome-release, chrome-beta.  Have not tested whether the chrome-release build would still work; it is at version 5.3.2 and I pretty much expect it won't work. ]

=====

Please read this as a request that the release builds of TM, in each 'store', should continue to know how to fall back to the old script injection APIs (or whatever methods they used).  Old browsers still get updated from new versions in the 'stores'; then they break.

I know I'm not the only person who will be running such old (and admittedly, ill-advised) configurations.  I'm lucky to have enough knowledge to somewhat defend myself; and here I am hoping to extend the benefits of that lucky knowledge to less knowledgable old-config users who wouldn't be able to defend themselves...

**Comment by derjanb** [comment]
I've updated the Opera version 14  days a go, but it's still review.

Thanks for debugging the issue. I'll add a workaround.

**Comment by derjanb** [comment]
Should be fixed at 5.4.6224 

Please install [Tampermonkey BETA](https://chromewebstore.google.com/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf) or force update it at the extensions page `chrome://extensions`.

For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

**Comment by slysnake96** [comment]
> Should be fixed at 5.4.6224
> 
> Please install [Tampermonkey BETA](https://chromewebstore.google.com/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf) or force update it at the extensions page `chrome://extensions`.
> 
> For a quick fix please export your settings and scripts as zip or (JSON) file at the "Utilities" tab and import it back at the fixed BETA version.

Importing settings and scripts from the non-BETA version to the BETA version causes the BETA version to crash and fail the import.

**Comment by derjanb** [comment]
@slysnake96 I can not reproduce this. Would it be possible to sent the backup to kontakt<at>tampermonkey.net?

**Comment by slysnake96** [comment]
> kontakt<at>tampermonkey.net

I have sent my backup TXT file via the email address you supplied, I sent the TXT file because I can't send the backup zip via email because google blocks it.

**Comment by derjanb** [comment]
@slysnake96 Still can't reproduce. Importing the text file, exporting it as zip, doing a factory reset and importing the zip all worked fine. 

Please try a new temporary profile and check whether it crashes there as well. If so, please open a new issue with some details about OS and browser.
