### ISSUE TITLE
Tampermonkey BETA  4.7.5798 stop show scripts lists

### ISSUE THREAD

**Issue by RX-3200** [Tampermonkey/tampermonkey#569]
## Expected Behavior
• Extension button onmousedown show scripts (if some scripts loaded in page)
• Extension panel of all installed scripts show scripts table

## Actual Behavior
• Extension button onmousedown show small clear white rectangle (if some scripts loaded in page)
• Extension panel of all installed scripts show "Please wait" only

## Specifications

- Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.170 Safari/537.36 OPR/53.0.2907.110
- TM: Tampermonkey BETA  4.7.5798
- OS: Win7x64

## Console log

background.html:1

Error in response to management.getAll: TypeError: Cannot read property 'join' of null
    at Object.determineOriginOfUrl (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:141:138)
    at Object.determineOrigin (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:137:308)
    at chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:247:386
    at ra (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:246:59)
    at Object.root (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:242:332)
    at chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:229:155
    at Object.<anonymous> (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/promise.js:5:61)
    at Array.f.check (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/promise.js:1:322)
    at Object.try_resolve (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/promise.js:3:383)
    at Object.getAll (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/rea/background.js:12:171)
    at Object.getAll (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/native.js:2:298)
    at Object.getAllUserscripts (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/native.js:2:410)
    at Object.natives (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:241:490)
    at chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:229:155
    at Object.<anonymous> (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/promise.js:5:61)
    at Array.f.check (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/promise.js:1:322)

**Comment by RX-3200** [comment]
## Specifications
- Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36 OPR/54.0.2952.41

## Console log
- (for ext button) background.html:1
Error in response to tabs.getSelected: TypeError: Cannot read property 'join' of null
    at Object.determineOriginOfUrl (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:141:138)
    at Object.determineOrigin (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:137:308)
    at chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:248:85
    at ra (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:246:59)
    at Object.root (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:234:380)
    at chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:229:155
    at Object.<anonymous> (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/promise.js:5:61)
    at Array.f.check (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/promise.js:1:322)
    at Array.f.push (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/promise.js:1:184)
    at Object.getSelected (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/rea/background.js:4:287)
    at Object.root (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:229:400)
    at chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:229:155
    at Object.create (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:245:431)
    at Object.exec (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:158:375)
    at g (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:176:31)

- (for table) background.html:1
Error in response to management.getAll: TypeError: Cannot read property 'join' of null
    at Object.determineOriginOfUrl (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:141:138)
    at Object.determineOrigin (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:137:308)
    at chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:247:386
    at ra (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:246:59)
    at Object.root (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:242:332)
    at chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:229:155
    at Object.<anonymous> (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/promise.js:5:61)
    at Array.f.check (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/promise.js:1:322)
    at Object.try_resolve (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/promise.js:3:383)
    at Object.getAll (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/rea/background.js:12:171)
    at Object.getAll (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/native.js:2:298)
    at Object.getAllUserscripts (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/native.js:2:410)
    at Object.natives (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:241:490)
    at chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:229:155
    at Object.<anonymous> (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/promise.js:5:61)
    at Array.f.check (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/promise.js:1:322)

**Comment by RX-3200** [comment]
Tampermonkey BETA 4.7.5811 fixed it, but new troubles in it:
https://github.com/Tampermonkey/tampermonkey/issues/575

**Comment by RX-3200** [comment]
Tampermonkey BETA 4.7.5811 fixed this, but new troubles in it: https://github.com/Tampermonkey/tampermonkey/issues/575
