### ISSUE TITLE
Tampermonkey BETA 4.7.5811 stop show full install window

### ISSUE THREAD

**Issue by RX-3200** [Tampermonkey/tampermonkey#575]
## Expected Behavior
• on press "Install" on scripts site - Tampermonkey show full install window with "script description" and "Install" button
• on script update - "compare" show script changes

## Actual Behavior
• on press "Install" on scripts site - Tampermonkey show only logo and clear pseudo-tab "Install" without text & buttons
• on script update - "compare" show nothing (it's clear = not load)

## Specifications

- Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36 OPR/54.0.2952.51
- TM: Tampermonkey BETA 4.7.5811
- OS: Win7x64

## Script

https://greasyfork.org/ru/scripts/36662-image-max-url
or any etc.

## Console log

- Error in event handler for webNavigation.onCommitted: TypeError: Cannot read property 'enabled' of undefined (background.html:1)
    at Object.commited (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:25:18)
    at k (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/background.js:284:112)

- Unchecked runtime.lastError while running tabs.remove: No tab with id: 187.  (background.html:1)
    at Object.remove (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/rea/background.js:3:418)
    at Object.close (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/asker.js:1:527)
    at Object.<anonymous> (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/asker.js:2:442)
    at Array.f.check (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/promise.js:1:322)
    at Object.try_resolve (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/promise.js:3:383)
    at Object.resolve (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/promise.js:4:79)
    at f (chrome-extension://gcalenpjmijncebpfijmoaglllgpjagf/asker.js:4:111)

**Comment by gatoremt** [comment]
I just get a blank white page with the Tempermonkey header
