### ISSUE TITLE
[bug] tampermonkey stoped by Cannot read property 'openAndWatch' of undefined

### ISSUE THREAD

**Issue by Cologler** [Tampermonkey/tampermonkey#712]
- Chromium: chrome
- TM: 4.8.41
- OS: win 10

![image](https://user-images.githubusercontent.com/10906962/57976821-3ba73e80-7a1c-11e9-93a5-408a0f5185f1.png)

``` js
Error handling response: TypeError: Cannot read property 'openAndWatch' of undefined
    at chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/syncinfo.js:17:46
    at Object.run (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/cloud.js:3:7)
    at chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/cloud.js:5:78
    at Object.start (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/cloud.js:16:199)
    at Object.listen (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/cloud.js:2:336)
    at Object.f (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/syncinfo.js:3:14)
    at Object.<anonymous> (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/promise.js:2:275)
    at Array.f.check (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/promise.js:1:322)
    at Array.f.push (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/promise.js:1:184)
    at Object.done (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/promise.js:1:396)
```

**Comment by Cologler** [comment]
Restart chrome can fixed this.
